workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: always
    - when: never

include:
  - local: ".gitlab/ci/common.yml"
  - local: ".gitlab/ci/runtime.yml"
  - local: ".gitlab/ci/verifier.yml"
  - local: ".gitlab/ci/nextcloud.yml"
  - local: ".gitlab/ci/manifest.yml"
